spring:
  application:
    name: Pay My Buddy
  datasource:
    url: jdbc:mysql://localhost:3306/pay_my_buddy
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port : 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'