spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/pay_my_buddy_dev
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  resources:
    static-locations: file:src/main/resources/static/
    cache-period: 0