spring:
  application:
    name: Pay My Buddy
  datasource:
    url: jdbc:mysql://${PAY_MY_BUDDY_DB_HOSTNAME}/pay_my_buddy_dev
    username: ${PAY_MY_BUDDY_DB_USERNAME}
    password: ${PAY_MY_BUDDY_DB_PSW}
    driver-class-name: com.mysql.jdbc.Driver

server:
  port : 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'